### PR TITLE
JMLL-1072 Update leaver thank you page to inform about GPC tasks

### PR DESCRIPTION
**Pull request by jafacakes2011**

### CODE REVIEW

**Comment by jafacakes2011** [comment]
Adds a new variable: GPC_RETURN_ADDRESS which I have added to all vaults as needed

**Comment by jafacakes2011** [comment]
Screenshot 2022-09-20 at 17 03 03

**Comment by jafacakes2011** [comment]
Screenshot 2022-09-20 at 17 03 46

**Review by rossmiller — APPROVED** [review]
LGTM!

**Pull request merged**
